STT 모델(WhisperX)에 Gradio 적용
develop-squad/MAIA pull request #1
Opened 2023-08-09 06:39 UTC by PlugDev77

* whisperx/core.py에 gradio 부분을 구현함
* 다음을 참고하여 M1 GPU를 활용하는 방법도 추가할 예정
  - https://github.com/m-bain/whisperX/issues/109

2023-08-09 06:45 UTC, Seongbuming commented
@PlugDev77 잘 돌아가?

2023-08-09 06:49 UTC, Seongbuming commented on main.py
> +        fn=whisper.fn,
이렇게 되면 Language Model 추론은 안거치는 거지?

2023-08-09 06:49 UTC, PlugDev77 commented
> @PlugDev77 잘 돌아가?

엉 나는 잘 돌아가는데 만약 패키지 없다던지 안돌아가면
MAIA 디렉토리 내에서 `pip install -e whisperx/` 하면 필요한거 설치 다 되고 돌아가는듯?

2023-08-09 06:50 UTC, PlugDev77 commented on main.py
> +        fn=whisper.fn,
아 맞아
우선 일단 빠르게 STT 잘 돌아가는 지 볼려하려고 LM 부분은 임시로 주석처리 해놨어

2023-08-09 06:51 UTC, Seongbuming commented
E2E로 하려면 requirements도 합쳐야해

2023-08-09 06:52 UTC, Seongbuming commented
> * 다음을 참고하여 M1 GPU를 활용하는 방법도 추가할 예정
>   
>   * [[Feature Request] Support M1 Mac's GPU m-bain/whisperX#109](https://github.com/m-bain/whisperX/issues/109)

M1 GPU는 안써도 돼 ㅋㅋㅋ 리눅스에서 구동하니까

2023-08-09 06:52 UTC, PlugDev77 commented
> E2E로 하려면 requirements도 합쳐야해

아 맞지 whisperx가 setup.py로 설치해서 그 부분도 수정을 해야겠다

2023-08-09 06:55 UTC, Seongbuming requested changes
- [ ] STT-LM Interaction @Seongbuming 
- [x] Integrate requirements @PlugDev77

2023-08-09 06:56 UTC, Seongbuming commented on main.py
> +        fn=whisper.fn,
오키 LM interaction은 내가 할게

2023-08-10 08:33 UTC, PlugDev77 commented
> * [ ]  STT-LM Interaction @Seongbuming
> * [ ]  Integrate requirements @PlugDev77

requirements 통합한 버전으로 feature/speech-to-text에 push했엉
Alpaca랑 whisperX 둘 다 잘 돌아가는거까지 확인했엉

2023-08-11 03:13 UTC, Seongbuming commented on MANIFEST.in
이건 루트 디렉터리에 나와있어야 하는 파일이야?

2023-08-11 03:15 UTC, Seongbuming commented on requirements.txt
> -git+https://github.com/huggingface/peft.git
PEFT 빠지면 안 돼

2023-08-12 05:56 UTC, PlugDev77 commented
@Seongbuming 다시 수정해서 requirements.txt에 통합했엉

2023-08-12 20:34 UTC, Seongbuming approved these changes

2023-08-12 20:36 UTC, merged