Implement Pairwise Model Evaluation Form and Reset feature
develop-squad/MAIA pull request #10
Opened 2023-09-04 10:30 UTC by PlugDev77

## Key Changes
- **Single Model Evaluation + Pairwise Model Evaluation Form**: Implemented a gradio form for Pairwise Model Evaluation

## Testing
- Conducted local tests and verified that the functionality is working as expected.

## Todo List
- Responding to bugs as they happen
- Refactoring if time permits

2023-09-05 22:32 UTC, Seongbuming requested changes
- [ ] A/B test는 제안하는 방법(`conversation/prompter.py`)와 아닌 것을 pairwise comparison하게 하고
- [ ] ChatGPT로 쌍을 이룰 것인지, PaLM으로 쌍을 이룰 것인지는 50:50 비율로 수집이 되도록 해줘!

2023-09-07 12:57 UTC, Seongbuming commented
@PlugDev77 a/b test 전까지 더 준비해야할 건 없나?

2023-09-07 23:52 UTC, PlugDev77 commented
@Seongbuming 
지금 틀만 만들어두고 실제 내용을 넣어야하는 부분들이 있어
그리고 좀 짜잘한거 좀 남은듯?

- [ ] IRB 동의에 들어갈 내용 반영
- [ ] 실험 설명 내용 반영
- [ ] 시스템 가이드 실제 이미지 반영(캡처 필요, 반영중)
- [ ] 번역이 필요한 부분 반영
- [ ] Model Evaluation 질문이 올바른지 체크
- [ ] 테스트 해보고 예외 처리

2023-09-08 00:02 UTC, Seongbuming requested changes
시스템 가이드는 이미지까지 쓸 필요는 없을 것 같은데, 이미지 없이 설명이 안되는 상황이 아니면 글로만 명확하게 설명하자
번역은 한국어로 써두면 내가 할게
아래 처리하고 re-request 해줘!

- [x]  IRB 동의에 들어갈 내용 반영
- [x]  실험 설명 내용 반영
- [x]  ~~시스템 가이드 실제 이미지 반영(캡처 필요, 반영중)~~
- [x]  ~~번역이 필요한 부분 반영~~
- [x]  Model Evaluation 질문이 올바른지 체크
- [ ]  테스트 해보고 예외 처리

2023-09-08 08:31 UTC, PlugDev77 commented
좀 더 명확하게 한 Todo List

- [ ] 상황에 대한 가이드에서 상황3 - 대화의 연속성에 대한 내용 추가
- [ ] System에서 각 상황을 보여주는 UI를 추가하고, 3가지 상황에 대해서 테스트할 수 있게 로직 변경
- [ ] 지속적으로 예외 처리(10개 문항중 9개만 평가했다던가 등등..)

2023-09-08 08:40 UTC, Seongbuming commented
> 기존의 작업들 중 다수는 완료했고, 좀 더 명확하게 명시한 Todo List
> 
> * [ ]  상황에 대한 가이드에서 상황3 - 대화의 연속성에 대한 내용 추가
> * [ ]  System에서 각 상황을 보여주는 UI를 추가하고, 3가지 상황에 대해서 테스트할 수 있게 로직 변경
> * [ ]  지속적으로 예외 처리(10개 문항중 9개만 평가했다던가 등등..)

과정에서 문헌조사가 뒷받침되면 논문에 논리 잡기도 좋을 거야

2023-09-11 08:57 UTC, Seongbuming approved these changes

2023-09-11 10:35 UTC, merged